// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSpqppqXI_YlPoZ6GxSahzQHU1cIkYFL8',
    appId: '1:613392205374:web:1104aacb571f896267336f',
    messagingSenderId: '613392205374',
    projectId: 'ambw-proyek',
    authDomain: 'ambw-proyek.firebaseapp.com',
    storageBucket: 'ambw-proyek.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXmiDnIuWq7sQCOBz0Fb1ZedzpbAaLunY',
    appId: '1:613392205374:android:fde1cecb53253cfc67336f',
    messagingSenderId: '613392205374',
    projectId: 'ambw-proyek',
    storageBucket: 'ambw-proyek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoAFjbEwcRLKE0ybUctiBtlWy1pQOWn4k',
    appId: '1:613392205374:ios:415fb3da4a2c488067336f',
    messagingSenderId: '613392205374',
    projectId: 'ambw-proyek',
    storageBucket: 'ambw-proyek.appspot.com',
    iosClientId: '613392205374-mh9h9meouilhbrpjuorg9pa370vsu2md.apps.googleusercontent.com',
    iosBundleId: 'com.example.ambwProyek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoAFjbEwcRLKE0ybUctiBtlWy1pQOWn4k',
    appId: '1:613392205374:ios:415fb3da4a2c488067336f',
    messagingSenderId: '613392205374',
    projectId: 'ambw-proyek',
    storageBucket: 'ambw-proyek.appspot.com',
    iosClientId: '613392205374-mh9h9meouilhbrpjuorg9pa370vsu2md.apps.googleusercontent.com',
    iosBundleId: 'com.example.ambwProyek',
  );
}
